changelog:
  exclude:
    labels:
      - this-is-an-unwanted-label
    authors:
      - CrazyCloudCraft
  categories:
    - title:  Dev Update > v2.4.31 beta 
      labels:
        - dev release
        - dependencies
    - title: Update > v2.4.32
      labels:
        - Offical Release
        - new-feature
        - bugfixing
    - title: BugFix > v2.4.31 
      labels:
        - bugfixing
    - title: Fast changes > v2.4.31
      labels:
        - duplicate
