name: WorldSystem
version: ${project.version}
author: Butzlabben
main: de.butzlabben.world.WorldSystem

api-version: 1.13

loadbefore: [FastAsyncWorldEdit, WorldEdit]

permissions:
  ws.*:
    default: op
    description: Gives '*'-Perms to all Commands
    children:
      ws.tp.*: true
      ws.get: true
      ws.sethome: true
      ws.tp.world: true
      ws.tp.toother: true
      ws.tp.other: true
      ws.build: true
      ws.gamemode: true
      ws.delete: true
      ws.lag: true
      ws.big: true
      ws.large: true
      ws.confirm: true
  ws.sethome:
    default: true
    description: 'You can set a different worldspawn'
  ws.tp.*:
    default: op
    description: You can teleport everything
    children:
      ws.tp.toother: true
      ws.tp.other: true
      ws.tp.world: true
  ws.build:
    default: op
    description: You can build on other Worlds without WorldPermissions
  ws.get:
    default: true
    description: You can create a world via /ws get
  ws.delete:
    default: op
    description: You can delete a world
  ws.gamemode:
    default: op
    description: You can change GameMode on other worlds
  ws.tp.other:
    default: op
    description: You can teleport other persons
  ws.tp.toother:
    default: op
    description: You can teleport across worlds
  ws.tp.world:
    default: op
    description: You can teleport to without rights World
  ws.lag:
    default: op
    description: You can see lag messages
  ws.big:
    default: op
    description: Gives you a bigger world (if set)
  ws.large:
    default: op
    children:
      ws.big: true
    description: Gives you a even bigger world (if set)
  ws.confirm:
    default: op
    description: You can confirm (if needed) an auto-update

default-permission: admin